FROM docker.1ms.run/node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs
COPY --chown=nextjs:nodejs ./dist ./
USER nextjs
EXPOSE 3000
ENV PORT=3000
ENTRYPOINT ["sh", "docker-entrypoint.sh"]
