import type { OutlinedInputThemePreset } from './types';

export const OUTLINED_INPUT_PRESETS: OutlinedInputThemePreset[] = [
  {
    name: 'Default',
    description: 'MUI default outlined style',
    config: {
      border: {
        borderColor: 'rgba(0, 0, 0, 0.23)',
        borderWidth: 1,
        borderRadius: '4px',
        hoverBorderColor: 'rgba(0, 0, 0, 0.87)',
        focusBorderColor: '#643DFF',
        errorBorderColor: '#d32f2f',
        disabledBorderColor: 'rgba(0, 0, 0, 0.26)',
      },
      input: {
        height: 56,
        padding: 16.5,
        fontSize: 16,
        fontWeight: 400,
        color: 'rgba(0, 0, 0, 0.87)',
        placeholderColor: 'rgba(0, 0, 0, 0.38)',
        disabledColor: 'rgba(0, 0, 0, 0.38)',
        backgroundColor: 'transparent',
      },
      adornment: { color: 'rgba(0, 0, 0, 0.54)', hoverColor: 'rgba(0, 0, 0, 0.87)', fontSize: 24 },
      notch: { legendFontSize: 12, legendColor: 'rgba(0, 0, 0, 0.6)', legendFocusColor: '#643DFF' },
    },
  },
  {
    name: 'Rounded',
    description: 'Pill-shaped with green accent',
    config: {
      border: {
        borderColor: '#22C55E',
        borderWidth: 2,
        borderRadius: '28px',
        hoverBorderColor: '#16A34A',
        focusBorderColor: '#15803D',
        errorBorderColor: '#EF4444',
        disabledBorderColor: '#D1D5DB',
      },
      input: {
        height: 52,
        padding: 14,
        fontSize: 15,
        fontWeight: 400,
        color: '#111827',
        placeholderColor: '#9CA3AF',
        disabledColor: '#9CA3AF',
        backgroundColor: 'transparent',
      },
      adornment: { color: '#22C55E', hoverColor: '#15803D', fontSize: 22 },
      notch: { legendFontSize: 12, legendColor: '#22C55E', legendFocusColor: '#15803D' },
    },
  },
  {
    name: 'Dark',
    description: 'Dark mode optimized',
    config: {
      border: {
        borderColor: '#374151',
        borderWidth: 1,
        borderRadius: '8px',
        hoverBorderColor: '#4B5563',
        focusBorderColor: '#8B5CF6',
        errorBorderColor: '#F87171',
        disabledBorderColor: '#1F2937',
      },
      input: {
        height: 56,
        padding: 16.5,
        fontSize: 16,
        fontWeight: 400,
        color: '#E5E7EB',
        placeholderColor: '#6B7280',
        disabledColor: '#4B5563',
        backgroundColor: '#111827',
      },
      adornment: { color: '#9CA3AF', hoverColor: '#D1D5DB', fontSize: 24 },
      notch: { legendFontSize: 12, legendColor: '#9CA3AF', legendFocusColor: '#A78BFA' },
    },
  },
  {
    name: 'Minimal',
    description: 'Clean thin border',
    config: {
      border: {
        borderColor: '#E5E7EB',
        borderWidth: 1,
        borderRadius: '2px',
        hoverBorderColor: '#9CA3AF',
        focusBorderColor: '#111827',
        errorBorderColor: '#EF4444',
        disabledBorderColor: '#F3F4F6',
      },
      input: {
        height: 44,
        padding: 12,
        fontSize: 14,
        fontWeight: 400,
        color: '#111827',
        placeholderColor: '#9CA3AF',
        disabledColor: '#D1D5DB',
        backgroundColor: 'transparent',
      },
      adornment: { color: '#6B7280', hoverColor: '#111827', fontSize: 20 },
      notch: { legendFontSize: 11, legendColor: '#6B7280', legendFocusColor: '#111827' },
    },
  },
  {
    name: 'Neon',
    description: 'Glowing purple neon',
    config: {
      border: {
        borderColor: '#7C3AED',
        borderWidth: 2,
        borderRadius: '8px',
        hoverBorderColor: '#8B5CF6',
        focusBorderColor: '#A78BFA',
        errorBorderColor: '#F87171',
        disabledBorderColor: '#4C1D95',
      },
      input: {
        height: 56,
        padding: 16.5,
        fontSize: 16,
        fontWeight: 500,
        color: '#E5E7EB',
        placeholderColor: '#7C3AED80',
        disabledColor: '#6D28D980',
        backgroundColor: '#0F0A1A',
      },
      adornment: { color: '#A78BFA', hoverColor: '#C4B5FD', fontSize: 22 },
      notch: { legendFontSize: 12, legendColor: '#A78BFA', legendFocusColor: '#C4B5FD' },
    },
  },
];
