/**
 * Poster Card Editor - Template Presets
 * 8 presets: 4 retro + 4 modern
 */

import type { TemplatePreset, TemplateStyle } from './types';

export const TEMPLATE_PRESETS: Record<TemplateStyle, TemplatePreset> = {
  // ── Retro ──────────────────────────────────────────────
  'bbs-terminal': {
    id: 'bbs-terminal',
    label: 'BBS 终端',
    labelEn: 'BBS Terminal',
    description: 'Green phosphor text on CRT black',
    category: 'retro',
    emoji: '🖥️',
    canvasSize: '3:4',
    background: { type: 'solid', color: '#0a0a0a' },
    elements: [
      {
        type: 'text',
        x: 40, y: 50, width: 1000, height: 60,
        rotation: 0, opacity: 100, zIndex: 2, locked: false, visible: true,
        content: 'RETRO BBS v2.4',
        fontFamily: "'Courier New', 'Lucida Console', monospace",
        fontSize: 36, fontWeight: 700, color: '#55ff55',
        textAlign: 'left', lineHeight: 1.5, letterSpacing: 2,
        backgroundColor: '', padding: 0,
      },
      {
        type: 'text',
        x: 60, y: 160, width: 960, height: 600,
        rotation: 0, opacity: 100, zIndex: 3, locked: false, visible: true,
        content: 'Your text here...',
        fontFamily: "'Courier New', 'Lucida Console', monospace",
        fontSize: 22, fontWeight: 400, color: '#55ff55',
        textAlign: 'left', lineHeight: 1.6, letterSpacing: 0,
        backgroundColor: '', padding: 0,
      },
      {
        type: 'decorative',
        x: 0, y: 0, width: 1080, height: 1440,
        rotation: 0, opacity: 15, zIndex: 1, locked: false, visible: true,
        decorativeType: 'scanlines', color: '#000000', strokeWidth: 1, spacing: 4,
      },
      {
        type: 'decorative',
        x: 20, y: 20, width: 1040, height: 1400,
        rotation: 0, opacity: 80, zIndex: 0, locked: false, visible: true,
        decorativeType: 'border', color: '#55ff55', strokeWidth: 2, spacing: 0,
      },
    ],
  },

  'c64': {
    id: 'c64',
    label: 'C64',
    labelEn: 'Commodore 64',
    description: 'BASIC programming style',
    category: 'retro',
    emoji: '💻',
    canvasSize: '4:3',
    background: { type: 'solid', color: '#40318D' },
    elements: [
      {
        type: 'decorative',
        x: 0, y: 0, width: 1080, height: 810,
        rotation: 0, opacity: 100, zIndex: 0, locked: false, visible: true,
        decorativeType: 'border', color: '#7C70DA', strokeWidth: 8, spacing: 0,
      },
      {
        type: 'text',
        x: 40, y: 40, width: 1000, height: 40,
        rotation: 0, opacity: 100, zIndex: 2, locked: false, visible: true,
        content: '10 PRINT "HELLO WORLD"',
        fontFamily: "'Courier New', 'Lucida Console', monospace",
        fontSize: 24, fontWeight: 400, color: '#7C70DA',
        textAlign: 'left', lineHeight: 1.6, letterSpacing: 0,
        backgroundColor: '', padding: 0,
      },
      {
        type: 'text',
        x: 40, y: 120, width: 1000, height: 500,
        rotation: 0, opacity: 100, zIndex: 3, locked: false, visible: true,
        content: '20 PRINT "Your text here"',
        fontFamily: "'Courier New', 'Lucida Console', monospace",
        fontSize: 22, fontWeight: 400, color: '#C9D487',
        textAlign: 'left', lineHeight: 1.6, letterSpacing: 0,
        backgroundColor: '', padding: 0,
      },
      {
        type: 'text',
        x: 40, y: 720, width: 400, height: 30,
        rotation: 0, opacity: 100, zIndex: 2, locked: false, visible: true,
        content: 'READY.',
        fontFamily: "'Courier New', 'Lucida Console', monospace",
        fontSize: 20, fontWeight: 400, color: '#C9D487',
        textAlign: 'left', lineHeight: 1.6, letterSpacing: 0,
        backgroundColor: '', padding: 0,
      },
    ],
  },

  'win95': {
    id: 'win95',
    label: 'Win95',
    labelEn: 'Windows 95',
    description: 'Classic Windows 95 window card',
    category: 'retro',
    emoji: '🪟',
    canvasSize: '4:3',
    background: { type: 'solid', color: '#008080' },
    elements: [
      {
        type: 'shape',
        x: 60, y: 40, width: 960, height: 700,
        rotation: 0, opacity: 100, zIndex: 1, locked: false, visible: true,
        shapeType: 'rectangle', fill: '#c0c0c0', stroke: '#ffffff', strokeWidth: 2, borderRadius: 0,
      },
      {
        type: 'shape',
        x: 62, y: 42, width: 956, height: 32,
        rotation: 0, opacity: 100, zIndex: 2, locked: false, visible: true,
        shapeType: 'rectangle', fill: '#000080', stroke: 'transparent', strokeWidth: 0, borderRadius: 0,
      },
      {
        type: 'text',
        x: 72, y: 44, width: 400, height: 28,
        rotation: 0, opacity: 100, zIndex: 3, locked: false, visible: true,
        content: 'Untitled - Notepad',
        fontFamily: "'MS Sans Serif', Tahoma, sans-serif",
        fontSize: 14, fontWeight: 700, color: '#ffffff',
        textAlign: 'left', lineHeight: 1, letterSpacing: 0,
        backgroundColor: '', padding: 4,
      },
      {
        type: 'text',
        x: 80, y: 100, width: 920, height: 600,
        rotation: 0, opacity: 100, zIndex: 3, locked: false, visible: true,
        content: 'Your content here...',
        fontFamily: "'MS Sans Serif', Tahoma, sans-serif",
        fontSize: 14, fontWeight: 400, color: '#000000',
        textAlign: 'left', lineHeight: 1.4, letterSpacing: 0,
        backgroundColor: '#ffffff', padding: 8,
      },
    ],
  },

  'mac-classic': {
    id: 'mac-classic',
    label: 'Mac Classic',
    labelEn: 'Mac Classic',
    description: 'Black & white System 6',
    category: 'retro',
    emoji: '🖥️',
    canvasSize: '1:1',
    background: { type: 'solid', color: '#dddddd' },
    elements: [
      {
        type: 'shape',
        x: 0, y: 0, width: 1080, height: 26,
        rotation: 0, opacity: 100, zIndex: 1, locked: false, visible: true,
        shapeType: 'rectangle', fill: '#ffffff', stroke: '#000000', strokeWidth: 1, borderRadius: 0,
      },
      {
        type: 'text',
        x: 20, y: 3, width: 200, height: 20,
        rotation: 0, opacity: 100, zIndex: 2, locked: false, visible: true,
        content: '🍎 File Edit View',
        fontFamily: "'Chicago', 'Geneva', Verdana, sans-serif",
        fontSize: 12, fontWeight: 700, color: '#000000',
        textAlign: 'left', lineHeight: 1, letterSpacing: 0,
        backgroundColor: '', padding: 2,
      },
      {
        type: 'decorative',
        x: 30, y: 50, width: 1020, height: 1000,
        rotation: 0, opacity: 100, zIndex: 0, locked: false, visible: true,
        decorativeType: 'border', color: '#000000', strokeWidth: 1, spacing: 0,
      },
      {
        type: 'text',
        x: 60, y: 100, width: 960, height: 800,
        rotation: 0, opacity: 100, zIndex: 2, locked: false, visible: true,
        content: 'Your text here...',
        fontFamily: "'Chicago', 'Geneva', Verdana, sans-serif",
        fontSize: 16, fontWeight: 400, color: '#000000',
        textAlign: 'left', lineHeight: 1.5, letterSpacing: 0,
        backgroundColor: '', padding: 0,
      },
    ],
  },

  // ── Modern ─────────────────────────────────────────────
  'modern-minimal': {
    id: 'modern-minimal',
    label: '极简',
    labelEn: 'Minimal',
    description: 'Clean white with large serif text',
    category: 'modern',
    emoji: '✨',
    canvasSize: '1:1',
    background: { type: 'solid', color: '#fafafa' },
    elements: [
      {
        type: 'shape',
        x: 160, y: 140, width: 760, height: 1,
        rotation: 0, opacity: 40, zIndex: 0, locked: false, visible: true,
        shapeType: 'line', fill: 'transparent', stroke: '#cccccc', strokeWidth: 1, borderRadius: 0,
      },
      {
        type: 'text',
        x: 80, y: 200, width: 920, height: 400,
        rotation: 0, opacity: 100, zIndex: 2, locked: false, visible: true,
        content: 'Your text here...',
        fontFamily: "'Noto Serif SC', 'Georgia', serif",
        fontSize: 36, fontWeight: 400, color: '#1a1a1a',
        textAlign: 'center', lineHeight: 1.8, letterSpacing: 2,
        backgroundColor: '', padding: 0,
      },
      {
        type: 'shape',
        x: 520, y: 650, width: 40, height: 6,
        rotation: 0, opacity: 100, zIndex: 1, locked: false, visible: true,
        shapeType: 'rectangle', fill: '#643DFF', stroke: 'transparent', strokeWidth: 0, borderRadius: 3,
      },
    ],
  },

  'gradient-modern': {
    id: 'gradient-modern',
    label: '渐变',
    labelEn: 'Gradient',
    description: 'Modern gradient with white text',
    category: 'modern',
    emoji: '🌈',
    canvasSize: '3:4',
    background: {
      type: 'gradient',
      angle: 135,
      stops: [
        { color: '#667eea', position: 0 },
        { color: '#764ba2', position: 100 },
      ],
    },
    elements: [
      {
        type: 'text',
        x: 80, y: 400, width: 920, height: 400,
        rotation: 0, opacity: 100, zIndex: 2, locked: false, visible: true,
        content: 'Your text here...',
        fontFamily: "'Noto Sans SC', 'PingFang SC', sans-serif",
        fontSize: 42, fontWeight: 700, color: '#ffffff',
        textAlign: 'center', lineHeight: 1.5, letterSpacing: 2,
        backgroundColor: '', padding: 0,
      },
      {
        type: 'shape',
        x: 0, y: 0, width: 1080, height: 1440,
        rotation: 0, opacity: 8, zIndex: 0, locked: false, visible: true,
        shapeType: 'rectangle', fill: '#000000', stroke: 'transparent', strokeWidth: 0, borderRadius: 0,
      },
    ],
  },

  'glassmorphism': {
    id: 'glassmorphism',
    label: '毛玻璃',
    labelEn: 'Glassmorphism',
    description: 'Frosted glass card over colorful background',
    category: 'modern',
    emoji: '🔮',
    canvasSize: '1:1',
    background: {
      type: 'gradient',
      angle: 45,
      stops: [
        { color: '#f093fb', position: 0 },
        { color: '#f5576c', position: 50 },
        { color: '#ffd194', position: 100 },
      ],
    },
    elements: [
      {
        type: 'shape',
        x: 140, y: 200, width: 800, height: 680,
        rotation: 0, opacity: 100, zIndex: 1, locked: false, visible: true,
        shapeType: 'rectangle',
        fill: 'rgba(255,255,255,0.15)', stroke: 'rgba(255,255,255,0.3)',
        strokeWidth: 1, borderRadius: 24,
      },
      {
        type: 'text',
        x: 180, y: 300, width: 720, height: 400,
        rotation: 0, opacity: 100, zIndex: 2, locked: false, visible: true,
        content: 'Your text here...',
        fontFamily: "'Noto Sans SC', 'PingFang SC', sans-serif",
        fontSize: 36, fontWeight: 600, color: '#ffffff',
        textAlign: 'center', lineHeight: 1.6, letterSpacing: 1,
        backgroundColor: '', padding: 0,
      },
    ],
  },

  'poster-bold': {
    id: 'poster-bold',
    label: '海报',
    labelEn: 'Poster Bold',
    description: 'High contrast, oversized text',
    category: 'modern',
    emoji: '🎨',
    canvasSize: '3:4',
    background: { type: 'solid', color: '#ff4757' },
    elements: [
      {
        type: 'shape',
        x: -200, y: -60, width: 1400, height: 200,
        rotation: -3, opacity: 15, zIndex: 0, locked: false, visible: true,
        shapeType: 'rectangle', fill: '#000000', stroke: 'transparent', strokeWidth: 0, borderRadius: 0,
      },
      {
        type: 'text',
        x: 60, y: 400, width: 960, height: 400,
        rotation: 0, opacity: 100, zIndex: 2, locked: false, visible: true,
        content: 'YOUR TEXT HERE',
        fontFamily: "'Noto Sans SC', 'PingFang SC', sans-serif",
        fontSize: 56, fontWeight: 900, color: '#ffffff',
        textAlign: 'center', lineHeight: 1.3, letterSpacing: 4,
        backgroundColor: '', padding: 0,
      },
      {
        type: 'shape',
        x: 490, y: 820, width: 100, height: 6,
        rotation: 0, opacity: 100, zIndex: 1, locked: false, visible: true,
        shapeType: 'rectangle', fill: '#ffd32a', stroke: 'transparent', strokeWidth: 0, borderRadius: 3,
      },
    ],
  },

  // ── Pinterest 2026 Trends ─────────────────────────────────
  'swiss-design': {
    id: 'swiss-design',
    label: '瑞士设计',
    labelEn: 'Swiss Design',
    description: 'Bauhaus-inspired geometric layout with bold typography',
    category: 'modern',
    emoji: '📐',
    canvasSize: '1:1',
    background: { type: 'solid', color: '#f5f0eb' },
    elements: [
      {
        type: 'shape',
        x: 0, y: 0, width: 1080, height: 360,
        rotation: 0, opacity: 100, zIndex: 0, locked: false, visible: true,
        shapeType: 'rectangle', fill: '#e63946', stroke: 'transparent', strokeWidth: 0, borderRadius: 0,
      },
      {
        type: 'shape',
        x: 60, y: 420, width: 440, height: 4,
        rotation: 0, opacity: 100, zIndex: 1, locked: false, visible: true,
        shapeType: 'rectangle', fill: '#1d1d1d', stroke: 'transparent', strokeWidth: 0, borderRadius: 0,
      },
      {
        type: 'text',
        x: 60, y: 60, width: 960, height: 280,
        rotation: 0, opacity: 100, zIndex: 2, locked: false, visible: true,
        content: 'DESIGN\nIS INTELLIGENCE\nMAKING ITSELF VISIBLE',
        fontFamily: "'Helvetica Neue', 'Arial', sans-serif",
        fontSize: 52, fontWeight: 900, color: '#f5f0eb',
        textAlign: 'left', lineHeight: 1.15, letterSpacing: -1,
        backgroundColor: '', padding: 0,
      },
      {
        type: 'text',
        x: 60, y: 460, width: 960, height: 500,
        rotation: 0, opacity: 100, zIndex: 2, locked: false, visible: true,
        content: 'Your text here...',
        fontFamily: "'Helvetica Neue', 'Arial', sans-serif",
        fontSize: 20, fontWeight: 300, color: '#1d1d1d',
        textAlign: 'left', lineHeight: 1.8, letterSpacing: 1,
        backgroundColor: '', padding: 0,
      },
      {
        type: 'shape',
        x: 800, y: 920, width: 220, height: 100,
        rotation: 0, opacity: 100, zIndex: 1, locked: false, visible: true,
        shapeType: 'rectangle', fill: '#1d1d1d', stroke: 'transparent', strokeWidth: 0, borderRadius: 0,
      },
      {
        type: 'text',
        x: 810, y: 935, width: 200, height: 70,
        rotation: 0, opacity: 100, zIndex: 2, locked: false, visible: true,
        content: '2026',
        fontFamily: "'Helvetica Neue', 'Arial', sans-serif",
        fontSize: 36, fontWeight: 900, color: '#f5f0eb',
        textAlign: 'center', lineHeight: 1.3, letterSpacing: 4,
        backgroundColor: '', padding: 0,
      },
    ],
  },

  'neon-cyber': {
    id: 'neon-cyber',
    label: '霓虹赛博',
    labelEn: 'Neon Cyber',
    description: 'Glowing neon text on deep dark background',
    category: 'modern',
    emoji: '💜',
    canvasSize: '9:16',
    background: { type: 'solid', color: '#0a0a1a' },
    elements: [
      {
        type: 'decorative',
        x: 0, y: 0, width: 1080, height: 1920,
        rotation: 0, opacity: 8, zIndex: 0, locked: false, visible: true,
        decorativeType: 'grid', color: '#643DFF', strokeWidth: 1, spacing: 60,
      },
      {
        type: 'shape',
        x: 0, y: 1400, width: 1080, height: 4,
        rotation: 0, opacity: 60, zIndex: 1, locked: false, visible: true,
        shapeType: 'rectangle', fill: '#00f0ff', stroke: 'transparent', strokeWidth: 0, borderRadius: 0,
      },
      {
        type: 'text',
        x: 60, y: 600, width: 960, height: 500,
        rotation: 0, opacity: 100, zIndex: 3, locked: false, visible: true,
        content: 'NEON\nNIGHTS',
        fontFamily: "'Helvetica Neue', 'Arial Black', sans-serif",
        fontSize: 96, fontWeight: 900, color: '#00f0ff',
        textAlign: 'left', lineHeight: 1.05, letterSpacing: -2,
        backgroundColor: '', padding: 0,
      },
      {
        type: 'text',
        x: 60, y: 1150, width: 960, height: 200,
        rotation: 0, opacity: 100, zIndex: 3, locked: false, visible: true,
        content: 'Your text here...',
        fontFamily: "'Courier New', monospace",
        fontSize: 18, fontWeight: 400, color: '#ff00e5',
        textAlign: 'left', lineHeight: 1.8, letterSpacing: 3,
        backgroundColor: '', padding: 0,
      },
      {
        type: 'shape',
        x: 60, y: 1400, width: 300, height: 60,
        rotation: 0, opacity: 100, zIndex: 2, locked: false, visible: true,
        shapeType: 'rectangle', fill: 'transparent', stroke: '#00f0ff', strokeWidth: 2, borderRadius: 0,
      },
      {
        type: 'text',
        x: 70, y: 1410, width: 280, height: 40,
        rotation: 0, opacity: 100, zIndex: 3, locked: false, visible: true,
        content: 'ENTER THE GRID',
        fontFamily: "'Courier New', monospace",
        fontSize: 14, fontWeight: 700, color: '#00f0ff',
        textAlign: 'center', lineHeight: 2.5, letterSpacing: 4,
        backgroundColor: '', padding: 0,
      },
    ],
  },

  'pastel-dream': {
    id: 'pastel-dream',
    label: '粉彩梦境',
    labelEn: 'Pastel Dream',
    description: 'Soft pastel gradient with gentle typography',
    category: 'modern',
    emoji: '🌸',
    canvasSize: '1:1',
    background: {
      type: 'gradient',
      angle: 160,
      stops: [
        { color: '#ffecd2', position: 0 },
        { color: '#fcb69f', position: 50 },
        { color: '#ee9ca7', position: 100 },
      ],
    },
    elements: [
      {
        type: 'shape',
        x: 240, y: 200, width: 600, height: 600,
        rotation: 0, opacity: 40, zIndex: 0, locked: false, visible: true,
        shapeType: 'circle', fill: '#ffffff', stroke: 'transparent', strokeWidth: 0, borderRadius: 0,
      },
      {
        type: 'text',
        x: 100, y: 340, width: 880, height: 400,
        rotation: 0, opacity: 100, zIndex: 2, locked: false, visible: true,
        content: 'Your text here...',
        fontFamily: "'Noto Serif SC', 'Georgia', serif",
        fontSize: 44, fontWeight: 400, color: '#5a3e36',
        textAlign: 'center', lineHeight: 1.6, letterSpacing: 3,
        backgroundColor: '', padding: 0,
      },
      {
        type: 'shape',
        x: 480, y: 800, width: 120, height: 4,
        rotation: 0, opacity: 60, zIndex: 1, locked: false, visible: true,
        shapeType: 'rectangle', fill: '#5a3e36', stroke: 'transparent', strokeWidth: 0, borderRadius: 2,
      },
      {
        type: 'text',
        x: 100, y: 860, width: 880, height: 100,
        rotation: 0, opacity: 60, zIndex: 2, locked: false, visible: true,
        content: '温柔而有力',
        fontFamily: "'Noto Sans SC', 'PingFang SC', sans-serif",
        fontSize: 16, fontWeight: 300, color: '#5a3e36',
        textAlign: 'center', lineHeight: 1.6, letterSpacing: 6,
        backgroundColor: '', padding: 0,
      },
    ],
  },

  'dark-luxury': {
    id: 'dark-luxury',
    label: '暗金奢华',
    labelEn: 'Dark Luxury',
    description: 'Dark background with gold accents',
    category: 'modern',
    emoji: '✨',
    canvasSize: '3:4',
    background: { type: 'solid', color: '#111111' },
    elements: [
      {
        type: 'decorative',
        x: 40, y: 40, width: 1000, height: 1360,
        rotation: 0, opacity: 100, zIndex: 0, locked: false, visible: true,
        decorativeType: 'border', color: '#c9a96e', strokeWidth: 1, spacing: 0,
      },
      {
        type: 'shape',
        x: 80, y: 80, width: 920, height: 1,
        rotation: 0, opacity: 40, zIndex: 1, locked: false, visible: true,
        shapeType: 'line', fill: 'transparent', stroke: '#c9a96e', strokeWidth: 1, borderRadius: 0,
      },
      {
        type: 'text',
        x: 80, y: 300, width: 920, height: 200,
        rotation: 0, opacity: 100, zIndex: 2, locked: false, visible: true,
        content: 'LUXURY',
        fontFamily: "'Georgia', 'Times New Roman', serif",
        fontSize: 72, fontWeight: 400, color: '#c9a96e',
        textAlign: 'center', lineHeight: 1.2, letterSpacing: 12,
        backgroundColor: '', padding: 0,
      },
      {
        type: 'shape',
        x: 440, y: 540, width: 200, height: 2,
        rotation: 0, opacity: 100, zIndex: 1, locked: false, visible: true,
        shapeType: 'rectangle', fill: '#c9a96e', stroke: 'transparent', strokeWidth: 0, borderRadius: 1,
      },
      {
        type: 'text',
        x: 80, y: 600, width: 920, height: 400,
        rotation: 0, opacity: 100, zIndex: 2, locked: false, visible: true,
        content: 'Your text here...',
        fontFamily: "'Noto Serif SC', 'Georgia', serif",
        fontSize: 20, fontWeight: 300, color: '#e0d5c1',
        textAlign: 'center', lineHeight: 2.0, letterSpacing: 2,
        backgroundColor: '', padding: 0,
      },
      {
        type: 'shape',
        x: 80, y: 1320, width: 920, height: 1,
        rotation: 0, opacity: 40, zIndex: 1, locked: false, visible: true,
        shapeType: 'line', fill: 'transparent', stroke: '#c9a96e', strokeWidth: 1, borderRadius: 0,
      },
    ],
  },

  'newspaper': {
    id: 'newspaper',
    label: '报纸风',
    labelEn: 'Newspaper',
    description: 'Classic newspaper editorial layout',
    category: 'modern',
    emoji: '📰',
    canvasSize: '3:4',
    background: { type: 'solid', color: '#f5f0e8' },
    elements: [
      {
        type: 'text',
        x: 40, y: 40, width: 1000, height: 80,
        rotation: 0, opacity: 100, zIndex: 2, locked: false, visible: true,
        content: 'THE DAILY POSTER',
        fontFamily: "'Georgia', 'Times New Roman', serif",
        fontSize: 48, fontWeight: 900, color: '#1a1a1a',
        textAlign: 'center', lineHeight: 1.2, letterSpacing: 2,
        backgroundColor: '', padding: 0,
      },
      {
        type: 'shape',
        x: 40, y: 130, width: 1000, height: 4,
        rotation: 0, opacity: 100, zIndex: 1, locked: false, visible: true,
        shapeType: 'rectangle', fill: '#1a1a1a', stroke: 'transparent', strokeWidth: 0, borderRadius: 0,
      },
      {
        type: 'shape',
        x: 40, y: 140, width: 1000, height: 2,
        rotation: 0, opacity: 100, zIndex: 1, locked: false, visible: true,
        shapeType: 'rectangle', fill: '#1a1a1a', stroke: 'transparent', strokeWidth: 0, borderRadius: 0,
      },
      {
        type: 'text',
        x: 40, y: 160, width: 1000, height: 40,
        rotation: 0, opacity: 70, zIndex: 2, locked: false, visible: true,
        content: 'VOL. CXXVI · NO. 42 · APRIL 2026 · SPECIAL EDITION',
        fontFamily: "'Georgia', 'Times New Roman', serif",
        fontSize: 11, fontWeight: 400, color: '#1a1a1a',
        textAlign: 'center', lineHeight: 3, letterSpacing: 2,
        backgroundColor: '', padding: 0,
      },
      {
        type: 'shape',
        x: 40, y: 210, width: 1000, height: 1,
        rotation: 0, opacity: 40, zIndex: 1, locked: false, visible: true,
        shapeType: 'line', fill: 'transparent', stroke: '#666666', strokeWidth: 1, borderRadius: 0,
      },
      {
        type: 'text',
        x: 40, y: 240, width: 1000, height: 500,
        rotation: 0, opacity: 100, zIndex: 2, locked: false, visible: true,
        content: 'Your headline here...',
        fontFamily: "'Georgia', 'Times New Roman', serif",
        fontSize: 56, fontWeight: 900, color: '#1a1a1a',
        textAlign: 'center', lineHeight: 1.1, letterSpacing: -1,
        backgroundColor: '', padding: 0,
      },
      {
        type: 'shape',
        x: 540, y: 780, width: 0, height: 500,
        rotation: 0, opacity: 30, zIndex: 1, locked: false, visible: true,
        shapeType: 'line', fill: 'transparent', stroke: '#999999', strokeWidth: 1, borderRadius: 0,
      },
      {
        type: 'text',
        x: 60, y: 820, width: 460, height: 400,
        rotation: 0, opacity: 100, zIndex: 2, locked: false, visible: true,
        content: 'Your content here...',
        fontFamily: "'Georgia', 'Times New Roman', serif",
        fontSize: 14, fontWeight: 400, color: '#333333',
        textAlign: 'left', lineHeight: 1.8, letterSpacing: 0,
        backgroundColor: '', padding: 0,
      },
    ],
  },

  'pop-art': {
    id: 'pop-art',
    label: '波普艺术',
    labelEn: 'Pop Art',
    description: 'Bold colors with halftone dot pattern',
    category: 'modern',
    emoji: '🎯',
    canvasSize: '1:1',
    background: { type: 'solid', color: '#ffdd00' },
    elements: [
      {
        type: 'shape',
        x: -100, y: -100, width: 600, height: 600,
        rotation: 0, opacity: 100, zIndex: 0, locked: false, visible: true,
        shapeType: 'circle', fill: '#ff3366', stroke: 'transparent', strokeWidth: 0, borderRadius: 0,
      },
      {
        type: 'shape',
        x: 600, y: 600, width: 600, height: 600,
        rotation: 0, opacity: 100, zIndex: 0, locked: false, visible: true,
        shapeType: 'circle', fill: '#00ccff', stroke: 'transparent', strokeWidth: 0, borderRadius: 0,
      },
      {
        type: 'decorative',
        x: 0, y: 0, width: 1080, height: 1080,
        rotation: 0, opacity: 15, zIndex: 1, locked: false, visible: true,
        decorativeType: 'dots', color: '#000000', strokeWidth: 1, spacing: 12,
      },
      {
        type: 'text',
        x: 60, y: 300, width: 960, height: 500,
        rotation: -3, opacity: 100, zIndex: 3, locked: false, visible: true,
        content: 'POP!',
        fontFamily: "'Helvetica Neue', 'Arial Black', sans-serif",
        fontSize: 160, fontWeight: 900, color: '#ffffff',
        textAlign: 'center', lineHeight: 1.0, letterSpacing: 8,
        backgroundColor: '', padding: 0,
      },
      {
        type: 'text',
        x: 60, y: 700, width: 960, height: 200,
        rotation: 0, opacity: 100, zIndex: 3, locked: false, visible: true,
        content: 'Your text here...',
        fontFamily: "'Helvetica Neue', 'Arial', sans-serif",
        fontSize: 28, fontWeight: 700, color: '#1a1a1a',
        textAlign: 'center', lineHeight: 1.5, letterSpacing: 2,
        backgroundColor: '', padding: 0,
      },
    ],
  },

  'tokyo-night': {
    id: 'tokyo-night',
    label: '东京夜色',
    labelEn: 'Tokyo Night',
    description: 'Japanese neon aesthetic with dark blue tones',
    category: 'modern',
    emoji: '🏯',
    canvasSize: '9:16',
    background: {
      type: 'gradient',
      angle: 180,
      stops: [
        { color: '#0f0c29', position: 0 },
        { color: '#302b63', position: 50 },
        { color: '#24243e', position: 100 },
      ],
    },
    elements: [
      {
        type: 'shape',
        x: 0, y: 700, width: 1080, height: 4,
        rotation: 0, opacity: 80, zIndex: 1, locked: false, visible: true,
        shapeType: 'rectangle', fill: '#ff007f', stroke: 'transparent', strokeWidth: 0, borderRadius: 0,
      },
      {
        type: 'text',
        x: 60, y: 200, width: 960, height: 500,
        rotation: 0, opacity: 100, zIndex: 3, locked: false, visible: true,
        content: '東京',
        fontFamily: "'Noto Sans SC', 'PingFang SC', 'Hiragino Sans', sans-serif",
        fontSize: 140, fontWeight: 900, color: '#ff007f',
        textAlign: 'left', lineHeight: 1.0, letterSpacing: 8,
        backgroundColor: '', padding: 0,
      },
      {
        type: 'text',
        x: 60, y: 780, width: 960, height: 400,
        rotation: 0, opacity: 100, zIndex: 3, locked: false, visible: true,
        content: 'Your text here...',
        fontFamily: "'Noto Sans SC', 'PingFang SC', sans-serif",
        fontSize: 24, fontWeight: 300, color: '#ffffff',
        textAlign: 'left', lineHeight: 1.8, letterSpacing: 2,
        backgroundColor: '', padding: 0,
      },
      {
        type: 'shape',
        x: 60, y: 1200, width: 200, height: 60,
        rotation: 0, opacity: 100, zIndex: 2, locked: false, visible: true,
        shapeType: 'rectangle', fill: '#00e5ff', stroke: 'transparent', strokeWidth: 0, borderRadius: 0,
      },
      {
        type: 'text',
        x: 60, y: 1210, width: 200, height: 40,
        rotation: 0, opacity: 100, zIndex: 3, locked: false, visible: true,
        content: '2026',
        fontFamily: "'Helvetica Neue', 'Arial', sans-serif",
        fontSize: 24, fontWeight: 900, color: '#0f0c29',
        textAlign: 'center', lineHeight: 1.5, letterSpacing: 6,
        backgroundColor: '', padding: 0,
      },
      {
        type: 'decorative',
        x: 0, y: 0, width: 1080, height: 1920,
        rotation: 0, opacity: 5, zIndex: 0, locked: false, visible: true,
        decorativeType: 'dots', color: '#ffffff', strokeWidth: 1, spacing: 30,
      },
    ],
  },

  'punk-riot': {
    id: 'punk-riot',
    label: '朋克反叛',
    labelEn: 'Punk Riot',
    description: 'Rebellious high-contrast cutout style',
    category: 'modern',
    emoji: '🎸',
    canvasSize: '3:4',
    background: { type: 'solid', color: '#1a1a1a' },
    elements: [
      {
        type: 'shape',
        x: -50, y: 300, width: 1180, height: 200,
        rotation: -2, opacity: 100, zIndex: 0, locked: false, visible: true,
        shapeType: 'rectangle', fill: '#ff1744', stroke: 'transparent', strokeWidth: 0, borderRadius: 0,
      },
      {
        type: 'shape',
        x: -50, y: 700, width: 1180, height: 200,
        rotation: 1, opacity: 100, zIndex: 0, locked: false, visible: true,
        shapeType: 'rectangle', fill: '#ff1744', stroke: 'transparent', strokeWidth: 0, borderRadius: 0,
      },
      {
        type: 'text',
        x: 40, y: 200, width: 1000, height: 300,
        rotation: -2, opacity: 100, zIndex: 2, locked: false, visible: true,
        content: 'NO RULES',
        fontFamily: "'Helvetica Neue', 'Arial Black', sans-serif",
        fontSize: 100, fontWeight: 900, color: '#ffffff',
        textAlign: 'left', lineHeight: 0.9, letterSpacing: -2,
        backgroundColor: '', padding: 0,
      },
      {
        type: 'text',
        x: 40, y: 560, width: 1000, height: 200,
        rotation: 0, opacity: 100, zIndex: 2, locked: false, visible: true,
        content: 'JUST CREATE',
        fontFamily: "'Helvetica Neue', 'Arial Black', sans-serif",
        fontSize: 80, fontWeight: 900, color: '#1a1a1a',
        textAlign: 'left', lineHeight: 1.0, letterSpacing: -1,
        backgroundColor: '', padding: 0,
      },
      {
        type: 'text',
        x: 40, y: 960, width: 1000, height: 400,
        rotation: 0, opacity: 100, zIndex: 2, locked: false, visible: true,
        content: 'Your text here...',
        fontFamily: "'Courier New', monospace",
        fontSize: 16, fontWeight: 400, color: '#cccccc',
        textAlign: 'left', lineHeight: 2.0, letterSpacing: 2,
        backgroundColor: '', padding: 0,
      },
      {
        type: 'decorative',
        x: 0, y: 0, width: 1080, height: 1440,
        rotation: 0, opacity: 12, zIndex: 1, locked: false, visible: true,
        decorativeType: 'scanlines', color: '#ffffff', strokeWidth: 1, spacing: 3,
      },
    ],
  },
};

export const TEMPLATE_LIST = Object.values(TEMPLATE_PRESETS);
