/**
 * Gradient Presets
 * Curated collection of 50+ gradients organized by category
 */

import type { GradientPreset } from './types';

export const GRADIENT_PRESETS: GradientPreset[] = [
  // ========================================
  // POPULAR - Most used gradients (15)
  // ========================================
  {
    id: 'aurora-dream',
    name: 'Aurora Dream',
    description: 'Magical blend of purples and blues',
    category: 'popular',
    tags: ['aurora', 'purple', 'blue', 'vibrant'],
    css: 'linear-gradient(135deg, #667eea 0%, #764ba2 50%, #f093fb 100%)',
    stops: [
      { color: '#667eea', position: 0 },
      { color: '#764ba2', position: 50 },
      { color: '#f093fb', position: 100 },
    ],
    type: 'linear',
    angle: 135,
    popularity: 98,
  },
  {
    id: 'sunset-glow',
    name: 'Sunset Glow',
    description: 'Warm sunset tones with orange and pink',
    category: 'popular',
    tags: ['sunset', 'orange', 'pink', 'warm'],
    css: 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
    stops: [
      { color: '#fa709a', position: 0 },
      { color: '#fee140', position: 100 },
    ],
    type: 'linear',
    angle: 135,
    popularity: 95,
  },
  {
    id: 'ocean-depths',
    name: 'Ocean Depths',
    description: 'Deep ocean blues and teals',
    category: 'popular',
    tags: ['ocean', 'blue', 'green', 'fresh'],
    css: 'linear-gradient(135deg, #11998e 0%, #38ef7d 100%)',
    stops: [
      { color: '#11998e', position: 0 },
      { color: '#38ef7d', position: 100 },
    ],
    type: 'linear',
    angle: 135,
    popularity: 92,
  },
  {
    id: 'cosmic-night',
    name: 'Cosmic Night',
    description: 'Deep space colors with purples and blues',
    category: 'popular',
    tags: ['cosmic', 'space', 'purple', 'dark'],
    css: 'linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)',
    stops: [
      { color: '#0f0c29', position: 0 },
      { color: '#302b63', position: 50 },
      { color: '#24243e', position: 100 },
    ],
    type: 'linear',
    angle: 135,
    popularity: 90,
  },
  {
    id: 'neon-pulse',
    name: 'Neon Pulse',
    description: 'Bright neon colors with pink and purple',
    category: 'popular',
    tags: ['neon', 'pink', 'purple', 'vibrant'],
    css: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
    stops: [
      { color: '#f093fb', position: 0 },
      { color: '#f5576c', position: 100 },
    ],
    type: 'linear',
    angle: 135,
    popularity: 88,
  },
  {
    id: 'mint-fresh',
    name: 'Mint Fresh',
    description: 'Cool mint and green tones',
    category: 'popular',
    tags: ['mint', 'green', 'fresh', 'cool'],
    css: 'linear-gradient(135deg, #00b09b 0%, #96c93d 100%)',
    stops: [
      { color: '#00b09b', position: 0 },
      { color: '#96c93d', position: 100 },
    ],
    type: 'linear',
    angle: 135,
    popularity: 85,
  },
  {
    id: 'peach-blush',
    name: 'Peach Blush',
    description: 'Soft peach and pink tones',
    category: 'popular',
    tags: ['peach', 'pink', 'soft', 'warm'],
    css: 'linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)',
    stops: [
      { color: '#ffecd2', position: 0 },
      { color: '#fcb69f', position: 100 },
    ],
    type: 'linear',
    angle: 135,
    popularity: 82,
  },
  {
    id: 'golden-hour',
    name: 'Golden Hour',
    description: 'Warm golden tones',
    category: 'popular',
    tags: ['golden', 'yellow', 'orange', 'warm'],
    css: 'linear-gradient(135deg, #f12711 0%, #f5af19 100%)',
    stops: [
      { color: '#f12711', position: 0 },
      { color: '#f5af19', position: 100 },
    ],
    type: 'linear',
    angle: 135,
    popularity: 80,
  },
  {
    id: 'royal-blue',
    name: 'Royal Blue',
    description: 'Deep blue to purple gradient',
    category: 'popular',
    tags: ['blue', 'purple', 'royal', 'elegant'],
    css: 'linear-gradient(135deg, #141e30 0%, #243b55 100%)',
    stops: [
      { color: '#141e30', position: 0 },
      { color: '#243b55', position: 100 },
    ],
    type: 'linear',
    angle: 135,
    popularity: 78,
  },
  {
    id: 'cool-blues',
    name: 'Cool Blues',
    description: 'Cool blue tones',
    category: 'popular',
    tags: ['blue', 'cool', 'calm', 'professional'],
    css: 'linear-gradient(135deg, #2193b0 0%, #6dd5ed 100%)',
    stops: [
      { color: '#2193b0', position: 0 },
      { color: '#6dd5ed', position: 100 },
    ],
    type: 'linear',
    angle: 135,
    popularity: 75,
  },
  {
    id: 'purple-haze',
    name: 'Purple Haze',
    description: 'Deep purple gradient',
    category: 'popular',
    tags: ['purple', 'vibrant', 'bold'],
    css: 'linear-gradient(135deg, #7028e4 0%, #e5b2ca 100%)',
    stops: [
      { color: '#7028e4', position: 0 },
      { color: '#e5b2ca', position: 100 },
    ],
    type: 'linear',
    angle: 135,
    popularity: 72,
  },
  {
    id: 'fire-watch',
    name: 'Fire Watch',
    description: 'Warm fire-like gradient',
    category: 'popular',
    tags: ['fire', 'red', 'orange', 'warm'],
    css: 'linear-gradient(135deg, #cb2d3e 0%, #ef473f 50%, #ff6b6b 100%)',
    stops: [
      { color: '#cb2d3e', position: 0 },
      { color: '#ef473f', position: 50 },
      { color: '#ff6b6b', position: 100 },
    ],
    type: 'linear',
    angle: 135,
    popularity: 70,
  },
  {
    id: 'emerald-water',
    name: 'Emerald Water',
    description: 'Fresh emerald green tones',
    category: 'popular',
    tags: ['green', 'emerald', 'fresh', 'nature'],
    css: 'linear-gradient(135deg, #348f50 0%, #56b4d3 100%)',
    stops: [
      { color: '#348f50', position: 0 },
      { color: '#56b4d3', position: 100 },
    ],
    type: 'linear',
    angle: 135,
    popularity: 68,
  },
  {
    id: 'lemon-twist',
    name: 'Lemon Twist',
    description: 'Bright yellow citrus gradient',
    category: 'popular',
    tags: ['yellow', 'lemon', 'bright', 'citrus'],
    css: 'linear-gradient(135deg, #f7971e 0%, #ffd200 100%)',
    stops: [
      { color: '#f7971e', position: 0 },
      { color: '#ffd200', position: 100 },
    ],
    type: 'linear',
    angle: 135,
    popularity: 65,
  },
  {
    id: 'rose-petals',
    name: 'Rose Petals',
    description: 'Soft rose pink gradient',
    category: 'popular',
    tags: ['rose', 'pink', 'soft', 'romantic'],
    css: 'linear-gradient(135deg, #e4c4b8 0%, #d6a5a0 100%)',
    stops: [
      { color: '#e4c4b8', position: 0 },
      { color: '#d6a5a0', position: 100 },
    ],
    type: 'linear',
    angle: 135,
    popularity: 62,
  },

  // ========================================
  // STRIPES - Diagonal stripe patterns (8)
  // ========================================
  {
    id: 'zebra-stripes',
    name: 'Zebra Stripes',
    description: 'Classic diagonal black and white stripes',
    category: 'stripes',
    tags: ['stripe', 'black', 'white', 'pattern'],
    css: 'repeating-linear-gradient(45deg, #000 0px, #000 10px, #fff 10px, #fff 20px)',
    stops: [
      { color: '#000000', position: 0 },
      { color: '#ffffff', position: 50 },
    ],
    type: 'linear',
    angle: 45,
  },
  {
    id: 'candy-stripes',
    name: 'Candy Stripes',
    description: 'Sweet pink and white stripes',
    category: 'stripes',
    tags: ['stripe', 'pink', 'candy', 'sweet'],
    css: 'repeating-linear-gradient(45deg, #ff69b4 0px, #ff69b4 10px, #fff 10px, #fff 20px)',
    stops: [
      { color: '#ff69b4', position: 0 },
      { color: '#ffffff', position: 50 },
    ],
    type: 'linear',
    angle: 45,
  },
  {
    id: 'barber-pole',
    name: 'Barber Pole',
    description: 'Classic red, white and blue barber pole',
    category: 'stripes',
    tags: ['stripe', 'red', 'blue', 'barber'],
    css: 'repeating-linear-gradient(45deg, #c41e3a 0px, #c41e3a 10px, #fff 10px, #fff 20px, #1e4d8c 20px, #1e4d8c 30px, #fff 30px, #fff 40px)',
    stops: [
      { color: '#c41e3a', position: 0 },
      { color: '#ffffff', position: 33 },
      { color: '#1e4d8c', position: 66 },
    ],
    type: 'linear',
    angle: 45,
  },
  {
    id: 'neon-stripes',
    name: 'Neon Stripes',
    description: 'Vibrant neon diagonal stripes',
    category: 'stripes',
    tags: ['stripe', 'neon', 'vibrant', 'cyber'],
    css: 'repeating-linear-gradient(45deg, #ff00ff 0px, #ff00ff 10px, #00ffff 10px, #00ffff 20px)',
    stops: [
      { color: '#ff00ff', position: 0 },
      { color: '#00ffff', position: 50 },
    ],
    type: 'linear',
    angle: 45,
  },
  {
    id: 'autumn-stripes',
    name: 'Autumn Stripes',
    description: 'Warm autumn color stripes',
    category: 'stripes',
    tags: ['stripe', 'autumn', 'warm', 'season'],
    css: 'repeating-linear-gradient(90deg, #d35400 0px, #d35400 20px, #e67e22 20px, #e67e22 40px, #f39c12 40px, #f39c12 60px)',
    stops: [
      { color: '#d35400', position: 0 },
      { color: '#e67e22', position: 50 },
      { color: '#f39c12', position: 100 },
    ],
    type: 'linear',
    angle: 90,
  },
  {
    id: 'ocean-stripes',
    name: 'Ocean Stripes',
    description: 'Calm blue ocean stripes',
    category: 'stripes',
    tags: ['stripe', 'ocean', 'blue', 'calm'],
    css: 'repeating-linear-gradient(180deg, #0077b6 0px, #0077b6 15px, #00a8e8 15px, #00a8e8 30px, #48cae4 30px, #48cae4 45px)',
    stops: [
      { color: '#0077b6', position: 0 },
      { color: '#00a8e8', position: 50 },
      { color: '#48cae4', position: 100 },
    ],
    type: 'linear',
    angle: 180,
  },
  {
    id: 'retro-stripes',
    name: 'Retro Stripes',
    description: '80s style retro stripes',
    category: 'stripes',
    tags: ['stripe', 'retro', 'vintage', '80s'],
    css: 'repeating-linear-gradient(-45deg, #ff6b6b 0px, #ff6b6b 15px, #feca57 15px, #feca57 30px, #48dbfb 30px, #48dbfb 45px, #ff9ff3 45px, #ff9ff3 60px)',
    stops: [
      { color: '#ff6b6b', position: 0 },
      { color: '#feca57', position: 33 },
      { color: '#48dbfb', position: 66 },
      { color: '#ff9ff3', position: 100 },
    ],
    type: 'linear',
    angle: -45,
  },
  {
    id: 'minimal-stripes',
    name: 'Minimal Stripes',
    description: 'Subtle gray stripes',
    category: 'stripes',
    tags: ['stripe', 'gray', 'minimal', 'subtle'],
    css: 'repeating-linear-gradient(90deg, #f5f5f5 0px, #f5f5f5 2px, transparent 2px, transparent 10px)',
    stops: [
      { color: '#f5f5f5', position: 0 },
      { color: 'transparent', position: 50 },
    ],
    type: 'linear',
    angle: 90,
  },

  // ========================================
  // CIRCULAR - Radial gradients (8)
  // ========================================
  {
    id: 'sunburst',
    name: 'Sunburst',
    description: 'Bright yellow sunburst effect',
    category: 'circular',
    tags: ['circular', 'sun', 'yellow', 'bright'],
    css: 'radial-gradient(circle, #ffeb3b 0%, #ff9800 50%, #f44336 100%)',
    stops: [
      { color: '#ffeb3b', position: 0 },
      { color: '#ff9800', position: 50 },
      { color: '#f44336', position: 100 },
    ],
    type: 'radial',
  },
  {
    id: 'bubblegum',
    name: 'Bubblegum',
    description: 'Sweet pink radial gradient',
    category: 'circular',
    tags: ['circular', 'pink', 'sweet', 'soft'],
    css: 'radial-gradient(circle, #ffc1e3 0%, #ff6b9d 50%, #c44569 100%)',
    stops: [
      { color: '#ffc1e3', position: 0 },
      { color: '#ff6b9d', position: 50 },
      { color: '#c44569', position: 100 },
    ],
    type: 'radial',
  },
  {
    id: 'electric-eye',
    name: 'Electric Eye',
    description: 'Electric blue circular gradient',
    category: 'circular',
    tags: ['circular', 'blue', 'electric', 'eye'],
    css: 'radial-gradient(circle, #00d4ff 0%, #090979 70%, #000000 100%)',
    stops: [
      { color: '#00d4ff', position: 0 },
      { color: '#090979', position: 70 },
      { color: '#000000', position: 100 },
    ],
    type: 'radial',
  },
  {
    id: 'honey-comb',
    name: 'Honey Comb',
    description: 'Warm honey radial gradient',
    category: 'circular',
    tags: ['circular', 'honey', 'gold', 'warm'],
    css: 'radial-gradient(circle, #ffd54f 0%, #ff9800 50%, #e65100 100%)',
    stops: [
      { color: '#ffd54f', position: 0 },
      { color: '#ff9800', position: 50 },
      { color: '#e65100', position: 100 },
    ],
    type: 'radial',
  },
  {
    id: 'aurora-circle',
    name: 'Aurora Circle',
    description: 'Northern lights in a circle',
    category: 'circular',
    tags: ['circular', 'aurora', 'green', 'purple'],
    css: 'radial-gradient(circle at 50% 50%, #43e97b 0%, #38f9d7 33%, #fa709a 66%, #fee140 100%)',
    stops: [
      { color: '#43e97b', position: 0 },
      { color: '#38f9d7', position: 33 },
      { color: '#fa709a', position: 66 },
      { color: '#fee140', position: 100 },
    ],
    type: 'radial',
  },
  {
    id: 'deep-space',
    name: 'Deep Space',
    description: 'Deep space radial effect',
    category: 'circular',
    tags: ['circular', 'space', 'dark', 'cosmic'],
    css: 'radial-gradient(circle, #1a1a2e 0%, #16213e 40%, #0f3460 70%, #533483 100%)',
    stops: [
      { color: '#1a1a2e', position: 0 },
      { color: '#16213e', position: 40 },
      { color: '#0f3460', position: 70 },
      { color: '#533483', position: 100 },
    ],
    type: 'radial',
  },
  {
    id: 'cherry-blossom',
    name: 'Cherry Blossom',
    description: 'Soft pink radial gradient',
    category: 'circular',
    tags: ['circular', 'cherry', 'pink', 'spring'],
    css: 'radial-gradient(circle, #ffd1dc 0%, #ffb6c1 50%, #ff69b4 100%)',
    stops: [
      { color: '#ffd1dc', position: 0 },
      { color: '#ffb6c1', position: 50 },
      { color: '#ff69b4', position: 100 },
    ],
    type: 'radial',
  },
  {
    id: 'tropical-haze',
    name: 'Tropical Haze',
    description: 'Tropical colors radial effect',
    category: 'circular',
    tags: ['circular', 'tropical', 'green', 'teal'],
    css: 'radial-gradient(circle, #a8edea 0%, #fed6e3 100%)',
    stops: [
      { color: '#a8edea', position: 0 },
      { color: '#fed6e3', position: 100 },
    ],
    type: 'radial',
  },

  // ========================================
  // ANGULAR - Conic/angular patterns (8)
  // ========================================
  {
    id: 'color-wheel',
    name: 'Color Wheel',
    description: 'Full color spectrum wheel',
    category: 'angular',
    tags: ['angular', 'rainbow', 'wheel', 'spectrum'],
    css: 'conic-gradient(red, yellow, lime, aqua, blue, magenta, red)',
    stops: [
      { color: '#ff0000', position: 0 },
      { color: '#ffff00', position: 16 },
      { color: '#00ff00', position: 32 },
      { color: '#00ffff', position: 48 },
      { color: '#0000ff', position: 64 },
      { color: '#ff00ff', position: 80 },
      { color: '#ff0000', position: 100 },
    ],
    type: 'conic',
  },
  {
    id: 'sunset-cone',
    name: 'Sunset Cone',
    description: 'Sunset colors in angular pattern',
    category: 'angular',
    tags: ['angular', 'sunset', 'orange', 'pink'],
    css: 'conic-gradient(from 0deg, #ff6b6b, #feca57, #48dbfb, #ff9ff3, #ff6b6b)',
    stops: [
      { color: '#ff6b6b', position: 0 },
      { color: '#feca57', position: 25 },
      { color: '#48dbfb', position: 50 },
      { color: '#ff9ff3', position: 75 },
      { color: '#ff6b6b', position: 100 },
    ],
    type: 'conic',
  },
  {
    id: 'pizza-slice',
    name: 'Pizza Slice',
    description: 'Italian flag colors angular',
    category: 'angular',
    tags: ['angular', 'italian', 'green', 'red'],
    css: 'conic-gradient(from 0deg, #009246, #009246 33%, #ffffff 33%, #ffffff 66%, #ce2b37 66%, #ce2b37)',
    stops: [
      { color: '#009246', position: 0 },
      { color: '#ffffff', position: 50 },
      { color: '#ce2b37', position: 100 },
    ],
    type: 'conic',
  },
  {
    id: 'neon-pie',
    name: 'Neon Pie',
    description: 'Neon colors in pie chart style',
    category: 'angular',
    tags: ['angular', 'neon', 'pie', 'vibrant'],
    css: 'conic-gradient(from 0deg, #ff00ff, #00ffff, #ffff00, #ff00ff)',
    stops: [
      { color: '#ff00ff', position: 0 },
      { color: '#00ffff', position: 33 },
      { color: '#ffff00', position: 66 },
      { color: '#ff00ff', position: 100 },
    ],
    type: 'conic',
  },
  {
    id: 'pastel-cone',
    name: 'Pastel Cone',
    description: 'Soft pastel angular gradient',
    category: 'angular',
    tags: ['angular', 'pastel', 'soft', 'gentle'],
    css: 'conic-gradient(from 45deg, #a8edea, #fed6e3, #d299c2, #fef9d7, #a8edea)',
    stops: [
      { color: '#a8edea', position: 0 },
      { color: '#fed6e3', position: 25 },
      { color: '#d299c2', position: 50 },
      { color: '#fef9d7', position: 75 },
      { color: '#a8edea', position: 100 },
    ],
    type: 'conic',
  },
  {
    id: 'retro-sun',
    name: 'Retro Sun',
    description: '80s retro sun rays',
    category: 'angular',
    tags: ['angular', 'retro', 'sun', '80s'],
    css: 'conic-gradient(from 0deg, #ff6b6b 0deg 30deg, #feca57 30deg 60deg, #ff6b6b 60deg 90deg, #feca57 90deg 120deg, #ff6b6b 120deg 150deg, #feca57 150deg 180deg, #ff6b6b 180deg 210deg, #feca57 210deg 240deg, #ff6b6b 240deg 270deg, #feca57 270deg 300deg, #ff6b6b 300deg 330deg, #feca57 330deg 360deg)',
    stops: [
      { color: '#ff6b6b', position: 0 },
      { color: '#feca57', position: 50 },
    ],
    type: 'conic',
  },
  {
    id: 'earth-tones',
    name: 'Earth Tones',
    description: 'Natural earth colors angular',
    category: 'angular',
    tags: ['angular', 'earth', 'natural', 'brown'],
    css: 'conic-gradient(from 0deg, #5d4037, #8d6e63, #a1887f, #d7ccc8, #5d4037)',
    stops: [
      { color: '#5d4037', position: 0 },
      { color: '#8d6e63', position: 25 },
      { color: '#a1887f', position: 50 },
      { color: '#d7ccc8', position: 75 },
      { color: '#5d4037', position: 100 },
    ],
    type: 'conic',
  },
  {
    id: 'cyber-pie',
    name: 'Cyber Pie',
    description: 'Cyberpunk style angular gradient',
    category: 'angular',
    tags: ['angular', 'cyber', 'cyberpunk', 'neon'],
    css: 'conic-gradient(from 180deg, #0ff 0deg 90deg, #f0f 90deg 180deg, #0ff 180deg 270deg, #f0f 270deg 360deg)',
    stops: [
      { color: '#00ffff', position: 0 },
      { color: '#ff00ff', position: 50 },
    ],
    type: 'conic',
  },

  // ========================================
  // SMOOTH - Standard smooth gradients (8)
  // ========================================
  {
    id: 'smooth-silk',
    name: 'Smooth Silk',
    description: 'Silky smooth purple gradient',
    category: 'smooth',
    tags: ['smooth', 'silk', 'purple', 'elegant'],
    css: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    stops: [
      { color: '#667eea', position: 0 },
      { color: '#764ba2', position: 100 },
    ],
    type: 'linear',
    angle: 135,
  },
  {
    id: 'velvet-dawn',
    name: 'Velvet Dawn',
    description: 'Soft velvet morning gradient',
    category: 'smooth',
    tags: ['smooth', 'velvet', 'dawn', 'soft'],
    css: 'linear-gradient(180deg, #a18cd1 0%, #fbc2eb 100%)',
    stops: [
      { color: '#a18cd1', position: 0 },
      { color: '#fbc2eb', position: 100 },
    ],
    type: 'linear',
    angle: 180,
  },
  {
    id: 'ocean-breeze',
    name: 'Ocean Breeze',
    description: 'Fresh ocean breeze gradient',
    category: 'smooth',
    tags: ['smooth', 'ocean', 'fresh', 'blue'],
    css: 'linear-gradient(120deg, #84fab0 0%, #8fd3f4 100%)',
    stops: [
      { color: '#84fab0', position: 0 },
      { color: '#8fd3f4', position: 100 },
    ],
    type: 'linear',
    angle: 120,
  },
  {
    id: 'mountain-mist',
    name: 'Mountain Mist',
    description: 'Misty mountain colors',
    category: 'smooth',
    tags: ['smooth', 'mountain', 'mist', 'nature'],
    css: 'linear-gradient(135deg, #757f9a 0%, #d7dde8 100%)',
    stops: [
      { color: '#757f9a', position: 0 },
      { color: '#d7dde8', position: 100 },
    ],
    type: 'linear',
    angle: 135,
  },
  {
    id: 'lavender-dream',
    name: 'Lavender Dream',
    description: 'Dreamy lavender tones',
    category: 'smooth',
    tags: ['smooth', 'lavender', 'dream', 'soft'],
    css: 'linear-gradient(135deg, #c3cfe2 0%, #c3cfe2 100%)',
    stops: [
      { color: '#e0c3fc', position: 0 },
      { color: '#c3cfe2', position: 100 },
    ],
    type: 'linear',
    angle: 135,
  },
  {
    id: 'warm-flannel',
    name: 'Warm Flannel',
    description: 'Cozy warm gradient',
    category: 'smooth',
    tags: ['smooth', 'warm', 'flannel', 'cozy'],
    css: 'linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)',
    stops: [
      { color: '#ffecd2', position: 0 },
      { color: '#fcb69f', position: 100 },
    ],
    type: 'linear',
    angle: 135,
  },
  {
    id: 'frost',
    name: 'Frost',
    description: 'Cool frost gradient',
    category: 'smooth',
    tags: ['smooth', 'frost', 'cool', 'ice'],
    css: 'linear-gradient(135deg, #e0eafc 0%, #cfdef3 100%)',
    stops: [
      { color: '#e0eafc', position: 0 },
      { color: '#cfdef3', position: 100 },
    ],
    type: 'linear',
    angle: 135,
  },
  {
    id: 'serenity',
    name: 'Serenity',
    description: 'Calm serenity gradient',
    category: 'smooth',
    tags: ['smooth', 'serenity', 'calm', 'peaceful'],
    css: 'linear-gradient(135deg, #9fa4c4 0%, #9fa4c4 100%)',
    stops: [
      { color: '#b8c6db', position: 0 },
      { color: '#9fa4c4', position: 100 },
    ],
    type: 'linear',
    angle: 135,
  },

  // ========================================
  // MESH - Complex multi-color blends (5)
  // ========================================
  {
    id: 'mesh-sunset',
    name: 'Mesh Sunset',
    description: 'Complex sunset mesh gradient',
    category: 'mesh',
    tags: ['mesh', 'sunset', 'complex', 'vibrant'],
    css: 'linear-gradient(135deg, #ff6b6b 0%, #feca57 25%, #48dbfb 50%, #ff9ff3 75%, #ff6b6b 100%)',
    stops: [
      { color: '#ff6b6b', position: 0 },
      { color: '#feca57', position: 25 },
      { color: '#48dbfb', position: 50 },
      { color: '#ff9ff3', position: 75 },
      { color: '#ff6b6b', position: 100 },
    ],
    type: 'linear',
    angle: 135,
  },
  {
    id: 'mesh-aurora',
    name: 'Mesh Aurora',
    description: 'Complex aurora mesh gradient',
    category: 'mesh',
    tags: ['mesh', 'aurora', 'complex', 'nature'],
    css: 'linear-gradient(135deg, #667eea 0%, #764ba2 20%, #f093fb 40%, #43e97b 60%, #38f9d7 80%, #667eea 100%)',
    stops: [
      { color: '#667eea', position: 0 },
      { color: '#764ba2', position: 20 },
      { color: '#f093fb', position: 40 },
      { color: '#43e97b', position: 60 },
      { color: '#38f9d7', position: 80 },
      { color: '#667eea', position: 100 },
    ],
    type: 'linear',
    angle: 135,
  },
  {
    id: 'mesh-ocean',
    name: 'Mesh Ocean',
    description: 'Complex ocean mesh gradient',
    category: 'mesh',
    tags: ['mesh', 'ocean', 'complex', 'blue'],
    css: 'linear-gradient(135deg, #0077b6 0%, #00a8e8 25%, #48cae4 50%, #90e0ef 75%, #0077b6 100%)',
    stops: [
      { color: '#0077b6', position: 0 },
      { color: '#00a8e8', position: 25 },
      { color: '#48cae4', position: 50 },
      { color: '#90e0ef', position: 75 },
      { color: '#0077b6', position: 100 },
    ],
    type: 'linear',
    angle: 135,
  },
  {
    id: 'mesh-forest',
    name: 'Mesh Forest',
    description: 'Complex forest mesh gradient',
    category: 'mesh',
    tags: ['mesh', 'forest', 'complex', 'green'],
    css: 'linear-gradient(135deg, #134e5e 0%, #71b280 33%, #2d5a27 66%, #134e5e 100%)',
    stops: [
      { color: '#134e5e', position: 0 },
      { color: '#71b280', position: 33 },
      { color: '#2d5a27', position: 66 },
      { color: '#134e5e', position: 100 },
    ],
    type: 'linear',
    angle: 135,
  },
  {
    id: 'mesh-fire',
    name: 'Mesh Fire',
    description: 'Complex fire mesh gradient',
    category: 'mesh',
    tags: ['mesh', 'fire', 'complex', 'hot'],
    css: 'linear-gradient(135deg, #ff0844 0%, #ffb199 25%, #ff0844 50%, #ffb199 75%, #ff0844 100%)',
    stops: [
      { color: '#ff0844', position: 0 },
      { color: '#ffb199', position: 25 },
      { color: '#ff0844', position: 50 },
      { color: '#ffb199', position: 75 },
      { color: '#ff0844', position: 100 },
    ],
    type: 'linear',
    angle: 135,
  },

  // ========================================
  // DARK - Dark mode friendly (6)
  // ========================================
  {
    id: 'dark-night',
    name: 'Dark Night',
    description: 'Deep dark night gradient',
    category: 'dark',
    tags: ['dark', 'night', 'black', 'deep'],
    css: 'linear-gradient(135deg, #0f0f0f 0%, #232526 50%, #0f0f0f 100%)',
    stops: [
      { color: '#0f0f0f', position: 0 },
      { color: '#232526', position: 50 },
      { color: '#0f0f0f', position: 100 },
    ],
    type: 'linear',
    angle: 135,
  },
  {
    id: 'midnight-city',
    name: 'Midnight City',
    description: 'Midnight city skyline gradient',
    category: 'dark',
    tags: ['dark', 'midnight', 'city', 'urban'],
    css: 'linear-gradient(135deg, #232526 0%, #414345 100%)',
    stops: [
      { color: '#232526', position: 0 },
      { color: '#414345', position: 100 },
    ],
    type: 'linear',
    angle: 135,
  },
  {
    id: 'dark-ocean',
    name: 'Dark Ocean',
    description: 'Deep dark ocean gradient',
    category: 'dark',
    tags: ['dark', 'ocean', 'deep', 'blue'],
    css: 'linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)',
    stops: [
      { color: '#0f2027', position: 0 },
      { color: '#203a43', position: 50 },
      { color: '#2c5364', position: 100 },
    ],
    type: 'linear',
    angle: 135,
  },
  {
    id: 'dark-violet',
    name: 'Dark Violet',
    description: 'Dark violet gradient',
    category: 'dark',
    tags: ['dark', 'violet', 'purple', 'elegant'],
    css: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)',
    stops: [
      { color: '#1a1a2e', position: 0 },
      { color: '#16213e', position: 50 },
      { color: '#0f3460', position: 100 },
    ],
    type: 'linear',
    angle: 135,
  },
  {
    id: 'dark-matter',
    name: 'Dark Matter',
    description: 'Deep space dark matter gradient',
    category: 'dark',
    tags: ['dark', 'matter', 'space', 'cosmic'],
    css: 'linear-gradient(135deg, #0c0c0c 0%, #1a1a2e 50%, #0c0c0c 100%)',
    stops: [
      { color: '#0c0c0c', position: 0 },
      { color: '#1a1a2e', position: 50 },
      { color: '#0c0c0c', position: 100 },
    ],
    type: 'linear',
    angle: 135,
  },
  {
    id: 'carbon',
    name: 'Carbon',
    description: 'Carbon fiber dark gradient',
    category: 'dark',
    tags: ['dark', 'carbon', 'fiber', 'texture'],
    css: 'linear-gradient(135deg, #1d1d1d 0%, #2d2d2d 50%, #1d1d1d 100%)',
    stops: [
      { color: '#1d1d1d', position: 0 },
      { color: '#2d2d2d', position: 50 },
      { color: '#1d1d1d', position: 100 },
    ],
    type: 'linear',
    angle: 135,
  },
];

/** Get all unique categories */
export const GRADIENT_CATEGORIES: Array<{ id: string; label: string }> = [
  { id: 'popular', label: 'Popular' },
  { id: 'stripes', label: 'Stripes' },
  { id: 'circular', label: 'Circular' },
  { id: 'angular', label: 'Angular' },
  { id: 'smooth', label: 'Smooth' },
  { id: 'mesh', label: 'Mesh' },
  { id: 'dark', label: 'Dark' },
];

/** Get all unique tags */
export const ALL_TAGS = Array.from(new Set(GRADIENT_PRESETS.flatMap((g) => g.tags)));
