/**
 * MUI Slider Theme Designer - Presets
 * Pre-configured slider theme presets
 */

import type { SliderThemeConfig, SliderThemePreset } from "./types";

export const SLIDER_THEME_PRESETS: SliderThemePreset[] = [
  {
    name: "Default",
    description: "MUI Default Style",
    config: {
      root: {
        height: 4,
        transitionDuration: "150ms",
      },
      rail: {
        height: 4,
        backgroundColor: "#919EAB",
        borderRadius: "2px",
        opacity: 1,
      },
      track: {
        height: 4,
        backgroundColor: "#643DFF",
        borderRadius: "2px",
        opacity: 1,
      },
      thumb: {
        width: 16,
        height: 16,
        color: "#643DFF",
        hoverColor: "#7B5FFF",
        activeColor: "#5A35E0",
        borderRadius: "50%",
        boxShadow: "0 2px 6px rgba(0,0,0,0.2)",
        borderWidth: 0,
        borderColor: "transparent",
      },
      mark: {
        width: 2,
        height: 2,
        backgroundColor: "#919EAB",
        borderRadius: "50%",
        activeColor: "#643DFF",
        labelFontSize: 12,
        labelColor: "rgba(0,0,0,0.6)",
      },
      valueLabel: {
        fontSize: 12,
        fontWeight: 500,
        color: "#fff",
        backgroundColor: "#643DFF",
        borderRadius: "4px",
        paddingX: 8,
        paddingY: 4,
        boxShadow: "0 2px 8px rgba(0,0,0,0.15)",
      },
      size: {
        small: {
          thumbWidth: 12,
          thumbHeight: 12,
          trackHeight: 3,
        },
        medium: {
          thumbWidth: 16,
          thumbHeight: 16,
          trackHeight: 4,
        },
      },
      exportVariant: "medium",
    },
  },
  {
    name: "Rounded",
    description: "Circular thumb with rounded track",
    config: {
      root: {
        height: 8,
        transitionDuration: "200ms",
      },
      rail: {
        height: 8,
        backgroundColor: "#E0E0E0",
        borderRadius: "4px",
        opacity: 1,
      },
      track: {
        height: 8,
        backgroundColor: "#22C55E",
        borderRadius: "4px",
        opacity: 1,
      },
      thumb: {
        width: 24,
        height: 24,
        color: "#22C55E",
        hoverColor: "#16A34A",
        activeColor: "#15803D",
        borderRadius: "50%",
        boxShadow: "0 4px 12px rgba(34, 197, 94, 0.4)",
        borderWidth: 4,
        borderColor: "#fff",
      },
      mark: {
        width: 4,
        height: 4,
        backgroundColor: "#BDBDBD",
        borderRadius: "50%",
        activeColor: "#22C55E",
        labelFontSize: 13,
        labelColor: "rgba(0,0,0,0.7)",
      },
      valueLabel: {
        fontSize: 14,
        fontWeight: 600,
        color: "#fff",
        backgroundColor: "#22C55E",
        borderRadius: "8px",
        paddingX: 12,
        paddingY: 6,
        boxShadow: "0 4px 12px rgba(34, 197, 94, 0.3)",
      },
      size: {
        small: {
          thumbWidth: 18,
          thumbHeight: 18,
          trackHeight: 6,
        },
        medium: {
          thumbWidth: 24,
          thumbHeight: 24,
          trackHeight: 8,
        },
      },
      exportVariant: "medium",
    },
  },
  {
    name: "Minimal",
    description: "Clean and minimal design",
    config: {
      root: {
        height: 2,
        transitionDuration: "100ms",
      },
      rail: {
        height: 2,
        backgroundColor: "#F0F0F0",
        borderRadius: "1px",
        opacity: 1,
      },
      track: {
        height: 2,
        backgroundColor: "#111827",
        borderRadius: "1px",
        opacity: 1,
      },
      thumb: {
        width: 12,
        height: 12,
        color: "#111827",
        hoverColor: "#374151",
        activeColor: "#000000",
        borderRadius: "50%",
        boxShadow: "none",
        borderWidth: 0,
        borderColor: "transparent",
      },
      mark: {
        width: 1,
        height: 1,
        backgroundColor: "#E5E7EB",
        borderRadius: "50%",
        activeColor: "#111827",
        labelFontSize: 11,
        labelColor: "rgba(0,0,0,0.5)",
      },
      valueLabel: {
        fontSize: 11,
        fontWeight: 400,
        color: "#111827",
        backgroundColor: "#F3F4F6",
        borderRadius: "2px",
        paddingX: 6,
        paddingY: 2,
        boxShadow: "0 1px 4px rgba(0,0,0,0.1)",
      },
      size: {
        small: {
          thumbWidth: 10,
          thumbHeight: 10,
          trackHeight: 1,
        },
        medium: {
          thumbWidth: 12,
          thumbHeight: 12,
          trackHeight: 2,
        },
      },
      exportVariant: "medium",
    },
  },
  {
    name: "Neon",
    description: "Glowing neon effect",
    config: {
      root: {
        height: 6,
        transitionDuration: "200ms",
      },
      rail: {
        height: 6,
        backgroundColor: "#1A1A2E",
        borderRadius: "3px",
        opacity: 1,
      },
      track: {
        height: 6,
        backgroundColor: "#FF00FF",
        borderRadius: "3px",
        opacity: 1,
      },
      thumb: {
        width: 20,
        height: 20,
        color: "#FF00FF",
        hoverColor: "#FF66FF",
        activeColor: "#CC00CC",
        borderRadius: "50%",
        boxShadow: "0 0 20px rgba(255, 0, 255, 0.8), 0 0 40px rgba(255, 0, 255, 0.4)",
        borderWidth: 3,
        borderColor: "#1A1A2E",
      },
      mark: {
        width: 3,
        height: 3,
        backgroundColor: "#2D2D44",
        borderRadius: "50%",
        activeColor: "#FF00FF",
        labelFontSize: 12,
        labelColor: "rgba(255,0,255,0.7)",
      },
      valueLabel: {
        fontSize: 13,
        fontWeight: 700,
        color: "#FF00FF",
        backgroundColor: "#1A1A2E",
        borderRadius: "6px",
        paddingX: 10,
        paddingY: 5,
        boxShadow: "0 0 20px rgba(255, 0, 255, 0.6)",
      },
      size: {
        small: {
          thumbWidth: 16,
          thumbHeight: 16,
          trackHeight: 4,
        },
        medium: {
          thumbWidth: 20,
          thumbHeight: 20,
          trackHeight: 6,
        },
      },
      exportVariant: "medium",
    },
  },
  {
    name: "Flat",
    description: "Flat design with square thumb",
    config: {
      root: {
        height: 6,
        transitionDuration: "150ms",
      },
      rail: {
        height: 6,
        backgroundColor: "#D1D5DB",
        borderRadius: "3px",
        opacity: 1,
      },
      track: {
        height: 6,
        backgroundColor: "#3B82F6",
        borderRadius: "3px",
        opacity: 1,
      },
      thumb: {
        width: 18,
        height: 18,
        color: "#3B82F6",
        hoverColor: "#2563EB",
        activeColor: "#1D4ED8",
        borderRadius: "4px",
        boxShadow: "0 2px 4px rgba(0,0,0,0.2)",
        borderWidth: 0,
        borderColor: "transparent",
      },
      mark: {
        width: 2,
        height: 2,
        backgroundColor: "#9CA3AF",
        borderRadius: "1px",
        activeColor: "#3B82F6",
        labelFontSize: 12,
        labelColor: "rgba(0,0,0,0.6)",
      },
      valueLabel: {
        fontSize: 12,
        fontWeight: 500,
        color: "#fff",
        backgroundColor: "#3B82F6",
        borderRadius: "4px",
        paddingX: 8,
        paddingY: 4,
        boxShadow: "0 2px 8px rgba(59, 130, 246, 0.3)",
      },
      size: {
        small: {
          thumbWidth: 14,
          thumbHeight: 14,
          trackHeight: 4,
        },
        medium: {
          thumbWidth: 18,
          thumbHeight: 18,
          trackHeight: 6,
        },
      },
      exportVariant: "medium",
    },
  },
];
