"use client";

import {
  PaletteOutlined,
  Gradient,
  ContentCopyOutlined,
  LayersOutlined,
  RoundedCorner,
  LensBlurOutlined,
  AnimationOutlined,
  Transform,
  TuneOutlined,
  CropOriginal,
  ViewQuilt,
  Contrast,
  BlurOn,
  Wallpaper,
  TextFieldsOutlined,
  PatternOutlined,
  TimelineOutlined,
  GridViewOutlined,
  StraightenOutlined,
  ImageOutlined,
  DevicesOutlined,
  StyleOutlined,
  FolderOutlined,
  AutoAwesomeOutlined,
  SentimentVeryDissatisfiedOutlined,
  BorderColorOutlined,
  SmartButton,
  ChatOutlined,
  BoltOutlined,
  ToggleOn,
  Tune as SliderIcon,
  TextFields as TextFieldIcon,
  Tab as TabIcon,
  ViewModule,
  Dashboard as DashboardIcon,
  EditOutlined,
  Bolt as AsyncIcon,
  Input as OutlinedInputIcon,
  MenuBookOutlined,
} from "@mui/icons-material";

// ----------------------------------------------------------------------

export type ToolNavItem = {
  title: string;
  path: string;
  icon: React.ReactElement;
  description?: string;
};

export const useToolsNavData = (): ToolNavItem[] => {
  return [
    {
      title: "沌联 Chat",
      path: "/chat",
      icon: <ChatOutlined />,
      description: "沌联大模型 AI 对话",
    },
    // {
    //   title: "Emotional Palette",
    //   path: "/emotional-palette",
    //   icon: <AutoAwesomeOutlined />,
    //   description: "Generate complete emotional atmosphere from mood keywords (colors, gradients, motion, typography)",
    // },
    // {
    //   title: "Card Generator",
    //   path: "/card-generator",
    //   icon: <StyleOutlined />,
    //   description: "AI-powered expressive card generator from text",
    // },
    // {
    //   title: "Roast Generator",
    //   path: "/roast-generator",
    //   icon: <SentimentVeryDissatisfiedOutlined />,
    //   description: "AI-powered roast generator with shareable cards",
    // },
    // {
    //   title: "Backgrounds",
    //   path: "/backgrounds",
    //   icon: <Wallpaper />,
    //   description: "Create beautiful background images with trianglify, particles, topography, and more",
    // },
    // {
    //   title: "SVG Generator",
    //   path: "/svgGenerator",
    //   icon: <BlurOn />,
    //   description: "Generate unique SVG design assets (blobs, waves, gradients)",
    // },
    // {
    //   title: "Colors",
    //   path: "/colors",
    //   icon: <PaletteOutlined />,
    //   description: "Generate color palettes from text descriptions",
    // },
    // {
    //   title: "Palette Workspace",
    //   path: "/workspace",
    //   icon: <FolderOutlined />,
    //   description: "Manage saved palettes with versioning and comparison",
    // },
    // {
    //   title: "Image Extract",
    //   path: "/image-extract",
    //   icon: <ImageOutlined />,
    //   description: "Extract colors and design tokens from images",
    // },
    // {
    //   title: "Gradients",
    //   path: "/gradients",
    //   icon: <Gradient />,
    //   description: "AI-powered gradient generation from text descriptions",
    // },
    // {
    //   title: "Gradient Editor",
    //   path: "/gradientEditor",
    //   icon: <Gradient />,
    //   description: "Visual CSS gradient editor with real-time preview",
    // },
    // {
    //   title: "HDR Gradient",
    //   path: "/hdr-gradient",
    //   icon: <Gradient />,
    //   description: "Advanced CSS HDR gradient builder with color spaces and multi-layer support",
    // },
    // {
    //   title: "Gradient Collection",
    //   path: "/gradient-collection",
    //   icon: <Gradient />,
    //   description: "Explore popular gradient collection",
    // },
    // {
    //   title: "Gradient Text",
    //   path: "/gradient-text",
    //   icon: <TextFieldsOutlined />,
    //   description: "Create gradient text effects with multiple CSS output formats",
    // },
    {
      title: "MUI Docs",
      path: "/docs",
      icon: <MenuBookOutlined />,
      description: "MUI v9 theme system analysis documentation",
    },
    {
      title: "Gradient Border",
      path: "/gradient-border",
      icon: <BorderColorOutlined />,
      description: "可视化渐变边框编辑器，支持多种渐变类型与实现方式",
    },
    // {
    //   title: "Poster Card",
    //   path: "/poster-card",
    //   icon: <DashboardIcon />,
    //   description: "Visual drag-and-drop poster & card maker with retro + modern templates",
    // },
    // {
    //   title: "SVG Editor",
    //   path: "/svg-editor",
    //   icon: <EditOutlined />,
    //   description: "Professional SVG icon editor with path editing, code sync, and export",
    // },
    {
      title: "Async React 19",
      path: "/async-react-demo",
      icon: <AsyncIcon />,
      description: "Interactive demos for useTransition & useActionState hooks",
    },
    {
      title: "MUI Button",
      path: "/muiButton",
      icon: <SmartButton />,
      description: "Visual MUI Button component designer with code export",
    },
    {
      title: "MUI Switch",
      path: "/muiSwitch",
      icon: <ToggleOn />,
      description: "MUI Switch 组件主题设计器",
    },
    {
      title: "MUI Slider",
      path: "/muiSlider",
      icon: <SliderIcon />,
      description: "MUI Slider 组件主题设计器",
    },
    {
      title: "MUI TextField",
      path: "/muiTextField",
      icon: <TextFieldIcon />,
      description: "MUI TextField 组件主题设计器",
    },
    {
      title: "MUI OutlinedInput",
      path: "/outlinedInput",
      icon: <OutlinedInputIcon />,
      description: "MUI OutlinedInput 组件主题设计器",
    },
    {
      title: "MUI Tabs",
      path: "/muiTabs",
      icon: <TabIcon />,
      description: "MUI Tabs 组件主题设计器",
    },
    {
      title: "MUI ToggleButton",
      path: "/muiToggleButton",
      icon: <ViewModule />,
      description: "MUI ToggleButton 组件主题设计器",
    },
    {
      title: "Box Shadow",
      path: "/boxShadow",
      icon: <LayersOutlined />,
      description: "Generate and customize CSS box shadows",
    },
    {
      title: "Border Beam",
      path: "/border-beam",
      icon: <BoltOutlined />,
      description: "边框光束动画效果生成器",
    },
    // {
    //   title: "Grid Pattern",
    //   path: "/grid-pattern",
    //   icon: <PatternOutlined />,
    //   description: "格子背景生成器 - 创建各种格子样式的背景图案",
    // },
    // {
    //   title: "Text Shadow",
    //   path: "/textShadow",
    //   icon: <TextFieldsOutlined />,
    //   description: "Text shadow visual editor",
    // },
    // {
    //   title: "Border Radius",
    //   path: "/borderRadius",
    //   icon: <RoundedCorner />,
    //   description: "Visual border radius editor with presets",
    // },
    {
      title: "Glass Effect",
      path: "/glassmorphism",
      icon: <LensBlurOutlined />,
      description: "Glassmorphism, liquid glass, and neumorphism CSS generator",
    },
    // {
    //   title: "Animations",
    //   path: "/animations",
    //   icon: <AnimationOutlined />,
    //   description: "Generate CSS keyframe animations",
    // },
    // {
    //   title: "Easing",
    //   path: "/easing",
    //   icon: <TimelineOutlined />,
    //   description: "Cubic-bezier easing curve editor",
    // },
    // {
    //   title: "Transform",
    //   path: "/transform",
    //   icon: <Transform />,
    //   description: "2D/3D transform editor",
    // },
    // {
    //   title: "Filters",
    //   path: "/filter",
    //   icon: <TuneOutlined />,
    //   description: "CSS filter effects generator",
    // },
    {
      title: "Clip Path",
      path: "/clipPath",
      icon: <CropOriginal />,
      description: "Interactive clip-path generator with draggable canvas, presets, and CSS export",
    },
    {
      title: "Patterns",
      path: "/patterns",
      icon: <PatternOutlined />,
      description: "SVG background pattern generator",
    },
    // {
    //   title: "Flexbox",
    //   path: "/flexbox",
    //   icon: <ViewQuilt />,
    //   description: "Flexbox layout playground",
    // },
    // {
    //   title: "Chart Editor",
    //   path: "/chartEditor",
    //   icon: <TimelineOutlined />,
    //   description: "Visual ECharts editor with live preview and code export",
    // },
    {
      title: "Grid",
      path: "/grid",
      icon: <GridViewOutlined />,
      description: "CSS Grid layout editor",
    },
    // {
    //   title: "Unit Converter",
    //   path: "/unitConverter",
    //   icon: <StraightenOutlined />,
    //   description: "px/rem/em/vw/vh unit converter",
    // },
    // {
    //   title: "Contrast",
    //   path: "/contrast",
    //   icon: <Contrast />,
    //   description: "WCAG color contrast checker",
    // },
    // {
    //   title: "Color Harmonies",
    //   path: "/color-harmonies",
    //   icon: <PaletteOutlined />,
    //   description: "Generate harmonious color schemes",
    // },
    // {
    //   title: "Spacing Scale",
    //   path: "/spacing-scale",
    //   icon: <StraightenOutlined />,
    //   description: "Generate spacing scales with different ratios",
    // },
    // {
    //   title: "Breakpoints",
    //   path: "/breakpoints",
    //   icon: <DevicesOutlined />,
    //   description: "Visualize and export responsive breakpoints",
    // },
    // {
    //   title: "Copy Tools",
    //   path: "/copy",
    //   icon: <ContentCopyOutlined />,
    //   description: "Text transformation and copy utilities",
    // },
  ];
};
